apiVersion: v1
kind: Service
metadata:
  name: kubeservice2
spec:
  selector:
    app: kubeusers2
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeusers2
  template:
    metadata:
      labels:
        app: kubeusers2
    spec:
      containers:
        - name: kubecontainer2
          image: diegopolverelli/abmusuarios:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://coderhouse:coderhouse@cluster0.v8ivmdl.mongodb.net/?retryWrites=true&w=majority&dbName=clase19
          imagePullPolicy: Always